#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Backend translation module for PARES report generation.
Supports English (en) and Spanish (es).
"""

from typing import Dict

# Translation dictionary for reports
TRANSLATIONS: Dict[str, Dict[str, str]] = {
    # ===== COMMON REPORT ELEMENTS =====
    "report.generated": {
        "en": "Generated",
        "es": "Generado"
    },
    "report.input_file": {
        "en": "Input File",
        "es": "Archivo de Entrada"
    },
    "report.analysis_scope": {
        "en": "Analysis Scope",
        "es": "Alcance del Análisis"
    },
    "report.toc": {
        "en": "Table of Contents",
        "es": "Tabla de Contenidos"
    },
    "report.footer": {
        "en": "Generated by PARES Pipeline | For internal analytical use",
        "es": "Generado por Pipeline PARES | Para uso analítico interno"
    },
    "report.no_data": {
        "en": "No data available",
        "es": "Sin datos disponibles"
    },
    "report.showing_rows": {
        "en": "Showing first {n} of {total} rows",
        "es": "Mostrando primeras {n} de {total} filas"
    },
    
    # ===== STORYLINE 1 =====
    "s1.title": {
        "en": "Storyline 1: Where to Act First?",
        "es": "Storyline 1: ¿Dónde Actuar Primero?"
    },
    "s1.subtitle": {
        "en": "Diagnostic Report - Evidence-Based Priority Analysis",
        "es": "Reporte Diagnóstico - Análisis de Priorización Basado en Evidencia"
    },
    "s1.scope": {
        "en": "Overall + By Grupo",
        "es": "General + Por Grupo"
    },
    "s1.executive_summary": {
        "en": "Executive Summary",
        "es": "Resumen Ejecutivo"
    },
    "s1.priority_analysis": {
        "en": "Priority Analysis",
        "es": "Análisis de Priorización"
    },
    "s1.threat_analysis": {
        "en": "Threat Analysis",
        "es": "Análisis de Amenazas"
    },
    "s1.capacity_analysis": {
        "en": "Adaptive Capacity Analysis",
        "es": "Análisis de Capacidad Adaptativa"
    },
    "s1.api_rankings": {
        "en": "Action Priority Index (API) Rankings",
        "es": "Rankings del Índice de Prioridad de Acción (API)"
    },
    "s1.threat_drivers": {
        "en": "Threat Drivers",
        "es": "Impulsores de Amenazas"
    },
    "s1.visualizations": {
        "en": "Visualizations",
        "es": "Visualizaciones"
    },
    "s1.qa_summary": {
        "en": "Data Quality Summary",
        "es": "Resumen de Calidad de Datos"
    },
    
    # ===== STORYLINE 2 =====
    "s2.title": {
        "en": "Storyline 2: Ecosystem-Service Lifelines",
        "es": "Storyline 2: Líneas críticas de servicios ecosistémicos para los medios de vida"
    },
    "s2.subtitle": {
        "en": "Diagnostic Report - Nature-Based Security Analysis",
        "es": "Reporte Diagnóstico - Análisis de Seguridad Basado en la Naturaleza"
    },
    "s2.scope": {
        "en": "Ecosystem Connectivity & Service Criticality",
        "es": "Conectividad Ecosistémica y Criticidad de Servicios"
    },
    "s2.executive_summary": {
        "en": "Executive Summary",
        "es": "Resumen Ejecutivo"
    },
    "s2.ecosystem_analysis": {
        "en": "Ecosystem Analysis",
        "es": "Análisis de Ecosistemas"
    },
    "s2.service_criticality": {
        "en": "Service Criticality",
        "es": "Criticidad de Servicios"
    },
    "s2.threats_vulnerability": {
        "en": "Threats & Vulnerability",
        "es": "Amenazas y Vulnerabilidad"
    },
    "s2.qa_summary": {
        "en": "Data Quality Summary",
        "es": "Resumen de Calidad de Datos"
    },
    
    # ===== STORYLINE 3 =====
    "s3.title": {
        "en": "Storyline 3: Equity & Differentiated Vulnerability",
        "es": "Storyline 3: Equidad y Vulnerabilidad Diferenciada"
    },
    "s3.subtitle": {
        "en": "Diagnostic Report - Who is Most Affected?",
        "es": "Reporte Diagnóstico - ¿Quién es Más Afectado?"
    },
    "s3.scope": {
        "en": "Differentiated Impacts, Service Access Barriers, Capacity Gaps",
        "es": "Impactos Diferenciados, Barreras de Acceso a Servicios, Brechas de Capacidad"
    },
    "s3.executive_summary": {
        "en": "Executive Summary",
        "es": "Resumen Ejecutivo"
    },
    "s3.differentiated_impacts": {
        "en": "Differentiated Impacts",
        "es": "Impactos Diferenciados"
    },
    "s3.service_access": {
        "en": "Service Access & Barriers",
        "es": "Acceso a Servicios y Barreras"
    },
    "s3.capacity_gaps": {
        "en": "Capacity Gaps",
        "es": "Brechas de Capacidad"
    },
    "s3.qa_summary": {
        "en": "Data Quality Summary",
        "es": "Resumen de Calidad de Datos"
    },
    "s3.stat.groups": {
        "en": "Vulnerable Groups Identified",
        "es": "Grupos Vulnerables Identificados"
    },
    "s3.stat.areas": {
        "en": "Geographic Areas (Grupos)",
        "es": "Áreas Geográficas (Grupos)"
    },
    "s3.stat.barriers": {
        "en": "Distinct Access Barriers",
        "es": "Barreras de Acceso Distintas"
    },
    "s3.stat.capacity": {
        "en": "Capacity Questions Analyzed",
        "es": "Preguntas de Capacidad Analizadas"
    },
    "s3.evi_title": {
        "en": "Equity Vulnerability Index (EVI) by Group",
        "es": "Índice de Vulnerabilidad de Equidad (EVI) por Grupo"
    },
    "s3.dif_desc": {
        "en": "This section identifies which subgroups are most affected by threats and their intensity of exposure.",
        "es": "Esta sección identifica qué subgrupos son más afectados por las amenazas y su intensidad de exposición."
    },
    "s3.impacted_subgroups": {
        "en": "Impacted Subgroups (Overall)",
        "es": "Subgrupos Afectados (General)"
    },
    "s3.intensity_subgroup": {
        "en": "Intensity by Subgroup",
        "es": "Intensidad por Subgrupo"
    },
    "s3.access_desc": {
        "en": "Analysis of common barriers and inclusion patterns reported by Medios de Vida.",
        "es": "Análisis de barreras comunes y patrones de inclusión reportados por Medios de Vida."
    },
    "s3.common_barriers": {
        "en": "Most Common Access Barriers",
        "es": "Barreras de Acceso Más Comunes"
    },
    "s3.barrier_rates": {
        "en": "Barrier & Inclusion Rates by Group",
        "es": "Tasas de Barreras e Inclusión por Grupo"
    },
    "s3.capacity_desc": {
        "en": "Scores reflect individual and collective capacity to adapt to threats (0 = Low Capacity, 1 = High Capacity).",
        "es": "Los puntajes reflejan la capacidad individual y colectiva de adaptarse a amenazas (0 = Baja Capacidad, 1 = Alta Capacidad)."
    },
    "s3.lowest_capacity": {
        "en": "Lowest Capacity Questions",
        "es": "Preguntas con Menor Capacidad"
    },
    "s3.capacity_livelihood": {
        "en": "Capacity by Livelihood",
        "es": "Capacidad por Medio de Vida"
    },
    "s3.no_dif_data": {
        "en": "No differentiated impact data available.",
        "es": "Sin datos de impactos diferenciados disponibles."
    },
    "s3.no_access_data": {
        "en": "No service access data available.",
        "es": "Sin datos de acceso a servicios disponibles."
    },
    "s3.no_capacity_data": {
        "en": "No capacity survey data available.",
        "es": "Sin datos de encuesta de capacidad disponibles."
    },
    "s3.requires_sheets": {
        "en": "This section requires sheets:",
        "es": "Esta sección requiere las hojas:"
    },
    "s3.ensure_columns": {
        "en": "Please ensure your input workbook contains these tables with columns like:",
        "es": "Por favor asegúrese que su libro de trabajo contenga estas tablas con columnas como:"
    },
    
    # ===== ABBREVIATIONS =====
    "abbr.title": {
        "en": "Abbreviations & Codes Reference",
        "es": "Referencia de Abreviaturas y Códigos"
    },
    
    # ===== TABLE HEADERS =====
    "table.grupo": {
        "en": "Group",
        "es": "Grupo"
    },
    "table.mdv": {
        "en": "Livelihood",
        "es": "Medio de Vida"
    },
    "table.threat": {
        "en": "Threat",
        "es": "Amenaza"
    },
    "table.score": {
        "en": "Score",
        "es": "Puntaje"
    },
    "table.count": {
        "en": "Count",
        "es": "Cantidad"
    },
    "table.rank": {
        "en": "Rank",
        "es": "Rango"
    },
    
    # ===== WARNINGS/ERRORS =====
    "warning.title": {
        "en": "Analysis Warnings",
        "es": "Advertencias del Análisis"
    },
    "qa.no_issues": {
        "en": "No quality issues detected.",
        "es": "No se detectaron problemas de calidad."
    },
}


def t(key: str, lang: str = "es", **kwargs) -> str:
    """
    Get translated string for a key.
    
    Args:
        key: Translation key
        lang: Language code ('en' or 'es')
        **kwargs: Interpolation parameters
        
    Returns:
        Translated string
    """
    entry = TRANSLATIONS.get(key)
    if not entry:
        return key
    
    text = entry.get(lang, entry.get("en", key))
    
    # Simple interpolation: {name} -> value
    for param, value in kwargs.items():
        text = text.replace(f"{{{param}}}", str(value))
    
    return text


def get_lang_from_request(lang: str = None) -> str:
    """
    Normalize language parameter.
    
    Args:
        lang: Language code from request
        
    Returns:
        Normalized language code ('en' or 'es')
    """
    if lang and lang.lower() in ("en", "english"):
        return "en"
    return "es"  # Default to Spanish
